version: '3'

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  employee-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_DSN: ${DB_DSN}

volumes:
  db_data:
